[tool.poetry]
name = "yesterdays-wisdom"
version = "0.1.0"
description = ""
authors = ["oscar-adserballe"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
protobuf = "4.21.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
